### ISSUE TITLE
Modify task gives error 500

### ISSUE THREAD

**Issue by smamczak** [indigo-dc/fgAPIServer#41]
http://docs.fgapis.apiary.io/#reference/v1.0/task/modify-a-task

```
curl -H "Authorization: Bearer XXX" http://Host:localhost/v1.0/tasks/237 -d '{"status":"CANCELLED"}' -X PATCH -v
*   Trying Host:localhost...
* TCP_NODELAY set
* Connected to Host:localhost (Host:localhost) port 80 (#0)
> PATCH /v1.0/tasks/237 HTTP/1.1
> Host:localhost
> User-Agent: curl/7.51.0
> Accept: */*
> Authorization: Bearer XXX
> Content-Length: 21
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 21 out of 21 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 500 INTERNAL SERVER ERROR
< Content-Type: text/html; charset=utf-8
< X-XSS-Protection: 0
< Connection: close
< Server: Werkzeug/0.11.11 Python/2.7.6
< Date: Mon, 20 Feb 2017 08:11:19 GMT
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"

...

UnboundLocalError

UnboundLocalError: local variable 'params' referenced before assignment

Traceback (most recent call last)

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__

                error = None
            ctx.auto_pop(error)
 
    def __call__(self, environ, start_response):
        """Shortcut for :attr:`wsgi_app`."""
        return self.wsgi_app(environ, start_response)
 
    def __repr__(self):
        return '<%s %r>' % (
            self.__class__.__name__,
            self.name,
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app

        try:
            try:
                response = self.full_dispatch_request()
            except Exception as e:
                error = e
                response = self.make_response(self.handle_exception(e))
            return response(environ, start_response)
        finally:
            if self.should_ignore_error(error):
                error = None
            ctx.auto_pop(error)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception

            # if we want to repropagate the exception, we can attempt to
            # raise it with the whole traceback in case we can do that
            # (the function was actually called from the except part)
            # otherwise, we just raise the error again
            if exc_value is e:
                reraise(exc_type, exc_value, tb)
            else:
                raise e
 
        self.log_exception((exc_type, exc_value, tb))
        if handler is None:


```

**Comment by ricsxn** [comment]
It was a bug due to a missing line, to apply a temporary fix, please apply chenges as reported below:

```
--- a/fgapiserver.py
+++ b/fgapiserver.py
@@ -1027,6 +1027,7 @@ def task_id(task_id=None):
         resp.headers['Content-type'] = 'application/json'
         return resp
     elif request.method == 'PATCH':
+        params = request.get_json()
         # PATCH on tasks accepts status change or on runtime_data
         new_status = params.get('status', None)
         if new_status is not None:
@@ -1099,7 +1100,6 @@ def task_id(task_id=None):
                     "message": "Not authorized to perform this request:\n%s" %
                                auth_msg}
             else:
-                params = request.get_json()
                 runtime_data = params.get('runtime_data', [])
                 fgapisrv_db = FGAPIServerDB(
                     db_host=fgapisrv_db_host,```

This fix will be available under Issue#30 branch
