### ISSUE TITLE
Cannot upload files to submitted task

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgAPIServer#76]
This issue concerns [FutureGatewayFramework/fgAPIServer](https://github.com/FutureGatewayFramework/fgAPIServer).

In my integration tests, I submit a new task and upload files to it. In the most recent version (in `date_format` branch) the file upload results in `500 Internal Server Error`. On the server side I can see this in the logs:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
TypeError: task_id_input() got an unexpected keyword argument 'task_id'
```

The [file upload logic](https://github.com/indigo-dc/indigoclient/blob/35861275bc434bd1b1e6a583ac3e17a890f0f725/src/main/java/pl/psnc/indigo/fg/api/restful/TasksAPI.java#L160) has not been changed in a long time and test used to work, so this is probably a regression.

**Comment by ricsxn** [comment]
Line 972 fgapiserver.py, replace:

`"task": task_id,`

with:

`"task": taskid,`

I do not have time to test it by my own, could you please try?
